-- ============================================================
-- Respostas das avaliações no banco — rodar no SQL Editor do Supabase
-- ============================================================
--
-- Problema: a nota do pré-teste era calculada no navegador e só o número
-- final ia pro banco (progresso_usuario.nota_pct). Sem as respostas:
--   • não dá pra auditar a nota
--   • sair no meio da prova e recomeçar zerava tudo — e o aluno já tinha
--     visto o gabarito, então refazia com 100% (nota inflada)
--
-- O que este script faz (NADA é apagado):
-- 1) Cria a tabela respostas_avaliacao — gêmea da tabela respostas dos
--    quizzes, mas apontando para questoes_avaliacao. A primeira resposta
--    de cada pergunta é definitiva (não há update nem delete).
-- 2) Recria a view v_desempenho_usuario_avaliacao:
--    • se o aluno tem respostas na tabela nova → nota calculada por elas
--      (fecha só quando respondeu TODAS as perguntas da avaliação)
--    • senão → continua valendo a nota antiga de progresso_usuario
--    A view segue retornando só quem tem nota fechada, como antes.

-- 1) Tabela de respostas das avaliações
create table if not exists public.respostas_avaliacao (
  id            bigint generated by default as identity primary key,
  user_id       uuid   not null references public.users(id) on delete cascade,
  avaliacao_id  bigint not null references public.avaliacoes(id) on delete cascade,
  question_id   bigint not null references public.questoes_avaliacao(id) on delete cascade,
  chosen_index  int    not null,
  is_correct    boolean not null,
  created_at    timestamptz not null default now(),
  unique (user_id, question_id)
);

create index if not exists idx_resp_av_user on public.respostas_avaliacao (user_id);
create index if not exists idx_resp_av_questao on public.respostas_avaliacao (question_id);

-- A primeira resposta é definitiva: pode inserir e ler, nunca alterar/apagar
alter table public.respostas_avaliacao enable row level security;

drop policy if exists "respostas_av_select" on public.respostas_avaliacao;
create policy "respostas_av_select" on public.respostas_avaliacao
  for select using (true);

drop policy if exists "respostas_av_insert" on public.respostas_avaliacao;
create policy "respostas_av_insert" on public.respostas_avaliacao
  for insert with check (true);

-- 2) View: nota calculada pelas respostas; nota antiga como retaguarda
-- (drop + create porque a view antiga tem colunas diferentes; view não guarda dados)
drop view if exists public.v_desempenho_usuario_avaliacao;
create view public.v_desempenho_usuario_avaliacao as
select * from (
  select
    u.id as user_id,
    a.id as avaliacao_id,
    a.titulo,
    coalesce(
      case
        when count(distinct q.id) > 0
         and count(distinct ra.question_id) = count(distinct q.id) then
          round(
            100.0 * sum(case when ra.is_correct then 1 else 0 end)::numeric
            / count(ra.id)::numeric
          )
      end,
      p.nota_pct
    ) as nota_pct
  from
    public.users u
    cross join public.avaliacoes a
    left join public.questoes_avaliacao q on q.avaliacao_id = a.id
    left join public.respostas_avaliacao ra on ra.question_id = q.id
      and ra.user_id = u.id
    left join public.progresso_usuario p on p.user_id = u.id
      and p.item_tipo = 'avaliacao'
      and p.item_id = a.id
  group by
    u.id, a.id, a.titulo, p.nota_pct
) t
where t.nota_pct is not null;
